define({
    selectFeatures: "Geometria",
    selectByAttribute: "Valor",
    results: "Resultados",
    searchLayer: "Buscar layer",
    searchType: "Buscar alias",
    selectFeaturesBy: "Seleccionar Featuares por",
    selectSpatial: "Espacial",
    search: "Buscar",
    clear: "Limpiar",
    clearBuffer: "Limpiar Buffer",
    zoomall: "Acercar a Todo",
    point: "Punto",
    line: "Linea",
    polyline: "Polil\u00EDnea",
    freehandPolyline: "Polil\u00EDnea Libre",
    triangle: "Triangulo",
    extent: "Extensi\u00F3n",
    circle: "Circulo",
    ellipse: "Elipse",
    polygon: "Pol\u00EDgono",
    freehandPolygon: "Pol\u00EDgono Libre",
    featuresSelected: "Elementos seleccionados: ",
    noResults: "Sin Resultados",
    searchError: "Busqueda Fallida !",
    searchResult: "Resultados de La Busqueda",
    useMultiGraphics: "Graficos Multiparte Habilitados",
    addTolerance: "Agregar Tolerancia de Busqueda a la selecci\u00F3n por punto",
    specifyParamsTip: "Especifique los par\u00E1metros para esta B\u00FAsqueda",
    and: "Y",
    friendlyDatePattern: "MM/dd/yyyy",
    stringOperatorIs: 'stringOperatorIs',
    stringOperatorIsNot: 'stringOperatorIsNot',
    stringOperatorStartsWith: 'stringOperatorStartsWith',
    stringOperatorEndsWith: 'stringOperatorEndsWith',
    stringOperatorContains: 'stringOperatorContains',
    stringOperatorDoesNotContain: 'stringOperatorDoesNotContain',
    stringOperatorIsBlank: 'stringOperatorIsBlank',
    stringOperatorIsNotBlank: 'stringOperatorIsNotBlank',
    dateOperatorIsOn: 'dateOperatorIsOn',
    dateOperatorIsNotOn: 'dateOperatorIsNotOn',
    dateOperatorIsBefore: 'dateOperatorIsBefore',
    dateOperatorIsAfter: 'dateOperatorIsAfter',
    dateOperatorDays: 'dateOperatorDays',
    dateOperatorWeeks: 'dateOperatorWeeks',
    dateOperatorMonths: 'dateOperatorMonths',
    dateOperatorInTheLast: 'dateOperatorInTheLast',
    dateOperatorNotInTheLast: 'dateOperatorNotInTheLast',
    dateOperatorIsBetween: 'dateOperatorIsBetween',
    dateOperatorIsNotBetween: 'dateOperatorIsNotBetween',
    dateOperatorIsBlank: 'dateOperatorIsBlank',
    dateOperatorIsNotBlank: 'dateOperatorIsNotBlank',
    numberOperatorIs: 'numberOperatorIs',
    numberOperatorIsNot: 'numberOperatorIsNot',
    numberOperatorIsAtLeast: 'numberOperatorIsAtLeast',
    numberOperatorIsLessThan: 'numberOperatorIsLessThan',
    numberOperatorIsAtMost: 'numberOperatorIsAtMost',
    numberOperatorIsGreaterThan: 'numberOperatorIsGreaterThan',
    numberOperatorIsBetween: 'numberOperatorIsBetween',
    numberOperatorIsNotBetween: 'numberOperatorIsNotBetween',
    numberOperatorIsBlank: 'numberOperatorIsBlank',
    numberOperatorIsNotBlank: 'numberOperatorIsNotBlank',
    bufferGraphic: 'Buffer Gr\u00E1fico',
    searchDistance: 'Aplicar Distancia de B\u00FAsqueda:',
    applyBuffer: 'Aplicar Buffer',
    searchEntities: 'Buscar Entidades de:',
    intersectMessage: 'No hay ning\u00FAn resultado para intersectarse , por favor completar una b\u00FAsqueda gr\u00E1fica o de texto primero.',
    spatialSearchErrorTitle: 'Error en Busqueda Espacial',
    bufferMessage: 'No hay ning\u00FAn resultado para el Buffer , por favor completar una b\u00FAsqueda gr\u00E1fica o de texto primero.',
    bufferSearchErrorTitle: 'Buffer error',
    spatialchoicemsg: '¿Quieres utilizar los gr\u00E1ficos de b\u00FAfer o la selecci\u00F3n de gr\u00E1ficos?',
    spatialchoicetitle: 'Escoger',
    buffergraphics: 'B\u00FAfer',
    selectiongraphics: 'Selecci\u00F3n',
    widgetversion: 'eSearch Widget Version Info',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Widget is designed to run in Web AppBuilder version',
    exporturl: 'Exportar URL de Busqueda',
    copyurlprompt: 'Copiar al portapapeles: Ctrl+C, Enter',
    limit2mapextent: 'Limite la Busqueda a la extensi\u00F3n del mapa',
    graphicgeomtypemsg1: 'No se admite la combinaci\u00F3n de  tipos de geometr\u00EDa como puntos, l\u00EDneas y pol\u00EDgonos.',
    graphicgeomtypemsg2: '¿Quieres continuar con lo que resultar\u00E1 en la limpieza de todos los gr\u00E1ficos anteriores elaborados?',
    cancel: 'cancelar',
    _continue: 'continuar',
    warning: 'Advertencia!',
    zoomErrorMessage: 'Los intentos de zoom autom\u00E1tico a los resultados de la b\u00FAsqueda han fallado.',
    addTextQuery: 'Incluir consulta de texto en los criterios de selecci\u00F3n',
    uniqueValues: 'Resiviendo valores \u00FAnicos',
    processingUnique: 'Procesando valores \u00FAnicos: ',
    of: ' de ',
    requiredTip: "El valor es requerido para ejecutar la b\u00FAsqueda",
    required: "Requirido",
    requiredWarning: "Valor requerido no encontrado",
    requiredErrorMessage: "Usted no a ingresado uno o mas valores requeridos",
    selectFeaturesFrom: "Usar graficos desde",
    eLocateTip: "Use el widget de gr\u00E1ficos existentes",
    createnewselection: "Crear resultados nuevos",
    addtoselection: "Adicionar a los resultados actuales",
    removefromselection: "Remover de los resultados actuales",
    mapServiceFailureTitle: "Fallo en la busqueda de capa de servicio de mapas",
    mapServicefailureMsg: "Los siguientes servicios de mapas de layers no responden: ",
    mapServicefailureMsg2: ". Debido a este fallo se eliminará la capa(s) de b\u00FAsqueda desde el widget.",
    removeResultMsg: "Remover resultados"
});
